# Generated by Django 5.0.9 on 2024-10-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
