# Generated by Django 5.0.9 on 2024-10-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customer_init_email_customer_init_email_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
