# Generated by Django 5.0.9 on 2024-10-22 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscritions",
            new_name="Subscriptions",
        ),
    ]
