# Generated by Django 5.0.9 on 2024-10-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0002_rename_subscritions_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="groups",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
