# Generated by Django 5.0.9 on 2024-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_alter_subscriptions_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
