# Generated by Django 5.0.9 on 2024-10-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0008_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
