# Generated by Django 5.0.9 on 2024-10-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0009_subscriptions_stripe_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscriptions",
            new_name="Subscription",
        ),
        migrations.CreateModel(
            name="SubscriptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("stripe_id", models.CharField(blank=True, max_length=120, null=True)),
                ("groups", models.ManyToManyField(to="auth.group")),
                (
                    "permissions",
                    models.ManyToManyField(
                        limit_choices_to={
                            "codename__in": ["elite", "pro", "basic"],
                            "content_type__app_label": "subscriptions",
                        },
                        to="auth.permission",
                    ),
                ),
            ],
        ),
    ]
