# Generated by Django 5.0.9 on 2024-10-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0012_alter_usersubscription_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="interval",
            field=models.CharField(
                choices=[("month", "Monthly"), ("year", "Yearly")],
                default="month",
                max_length=120,
            ),
        ),
    ]
