# Generated by Django 5.0.9 on 2024-10-23 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0014_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
