# Generated by Django 5.0.9 on 2024-10-23 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0016_alter_subscription_options_subscription_featured_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["subscription__order", "order", "featured", "-updated"]
            },
        ),
    ]
