# Generated by Django 5.0.9 on 2024-10-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_alter_subscriptionprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Features for pricing separated by new line ",
                null=True,
            ),
        ),
    ]
