# Generated by Django 5.0.9 on 2024-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0019_remove_subscriptionprice_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subtitle",
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
